### ISSUE TITLE
Collision with non world origin position appears in the wrong position

### ISSUE THREAD

**Issue by Sertion** [bikemurt/blender-godot-pipeline#11]
When importing collisions that are not at the world origin it appears in unpredictable positions.

The setup in Blender ([file](https://github.com/user-attachments/files/18263788/position-issue.zip)):
![blender](https://github.com/user-attachments/assets/fda94c9a-05c1-4326-a633-040eda9a8475)

The imported result in Godot:
![godot](https://github.com/user-attachments/assets/3537b470-0929-4dea-b38f-66cdf252634a)

The "bottom cylinder" is imported with a "flipped" `z` (Godot space) coordinate. All the other colliders appear at `0, 0, 0`.

**Comment by bikemurt** [comment]
Thanks for the feedback. I _thought_ I had tested compound collision shapes but something got lost in the mix (the merge was messy).

Just pushed a couple of commits that should help things:
https://github.com/bikemurt/blender-godot-pipeline/commit/6c7a0fc30a0598dd64ded387a6af74eaca990516
https://github.com/bikemurt/blender-godot-pipeline/commit/e4416799a3a602a99a47ddad7a28b710cc146b39

Those are fixed, and if you want, you can replace `SceneInit.gd` with the latest file from this repo and see if that helps importing.

One issue in your .blend file is that "Element" is composed of two separate shapes, with all vertices contained within the "Element" object:
![image](https://github.com/user-attachments/assets/9b4f66cd-22b1-4b89-8a02-9af0af55a682)

Primitive shapes are "wrapped" around the object's geometry, so in this case the cube and cylinder would need to be split (in Blender just select all the verts from one of the objects and press P -> Separate by Selection).

I've attached a "fixed" version of this .blend file, with a couple of other shapes added to test some things.

[position-issue.zip](https://github.com/user-attachments/files/18264597/position-issue.zip)

The two spheres I added test world origins, which should work fine:
![image](https://github.com/user-attachments/assets/56c1b348-94c8-49bb-9233-7c5cbe7f6837)

![image](https://github.com/user-attachments/assets/dfbe4abf-43ef-4536-90cb-6a937d58d854)

**Comment by Sertion** [comment]
Thank you for the quick response!

The changes works great for the example file, but the ["real file"](https://github.com/user-attachments/files/18265774/dinonugget.zip) that made me discover this issue still turns out a bit weird. It could be that I have misunderstood something.

How it looks in Blender:
![Dinonugget in Blender](https://github.com/user-attachments/assets/088540fa-9f6d-473e-97d1-12e0a684dc7d)

And how it turns out after I have replaced the `SceneInit.gd` in `res://addons/blender_godot_pipeline/`:
![Dinonugget in Godot](https://github.com/user-attachments/assets/f4823dd6-f2db-4b78-bae7-015e53b245b1)

As far as I can tell nothing i scaled, but it does look like something scales the position of the cylinder colliders.

**Comment by bikemurt** [comment]
I took a look at your .blend file, I think you just need to hit "Set Collisions" again before exporting:
![image](https://github.com/user-attachments/assets/f4833e4a-a037-4cab-9791-37aad152675e)

![image](https://github.com/user-attachments/assets/a50afec9-c07c-42a1-b7fb-f298d68176e1)

**Comment by Sertion** [comment]
Thanks a lot for checking the file and I am _so sorry_ it was something so stupid :(

Love the extension/addon so far!
